[pytest]                    # секция конфигурации pytest
markers =                   # регистрация кастомных маркеров
    smoke: быстрые тесты
    regression: полный регресс
# искать тесты только в папке tests
testpaths = tests
# автоматически добавлять флаги -s и -v при каждом запуске
addopts = -s -v